group: false
nametags: true
playerlist: false

Factions:
SimpleClans:
  ally: b
  member: '3'
  rival: c
  warring: '4'
SimpleClans2:
  ally: b
  member: '3'
  rival: c
  warring: '4'
Towny:
  ally: b
  enemy: c
xTeam:
  ally: b
  enemy: c
  neutral: f